//! A pattern is a glob that knows how to split itself into a prefix and join with a partial prefix

use std::collections::BTreeSet;
use std::sync::Arc;
use std::sync::atomic::AtomicUsize;

use anyhow::{Context as _, Result};
use aws_sdk_s3::types::Object;
use engine::ScanResult;
use glob::Glob;
use itertools::Itertools as _;
use regex::Regex;
use tokio::sync::Semaphore;
use tokio::sync::mpsc::UnboundedReceiver;
use tracing::{debug, trace, warn};

mod engine;
pub use engine::{Engine, S3Engine};

use crate::progress;
use crate::{S3Object, progressln};

mod glob;

#[cfg(test)]
mod proptests;

pub(crate) const GLOB_CHARS: &[char] = &['*', '?', '[', '{'];

/// The maximum number of prefixes that can be generated by the glob matcher
///
/// Checking that constructed prefixes exist is significantly slower than
/// scanning for objects.
const MAX_PREFIXES: usize = 100_000;

const MAX_CHECK_PREFIXES: usize = 10_000;

/// Parallelism is determined by the number of prefixes, and 50 is much faster
/// than 1
const DESIRED_MIN_PREFIXES: usize = 25;

/// Single-page LIST cap used for the per-prefix density probe at `**`.
///
/// 1000 is the maximum S3 honours for `max-keys`; if a prefix's full
/// content fits in one page we can resolve it in a single round-trip
/// without exploding into per-sub-prefix listings.
const PROBE_MAX_KEYS: i32 = 1000;

/// A thing that knows how to generate and filter S3 prefixes based on a glob pattern
#[derive(Debug, Clone)]
pub struct S3GlobMatcher {
    raw: String,
    delimiter: char,
    parts: Vec<glob::Glob>,
    regex: Regex,
    max_parallelism: usize,
    min_prefixes: usize,
    max_prefixes: usize,
    probe_max_keys: i32,
    /// True if no further listing needs to be done by the caller
    ///
    /// Generally anything that does not contain a ** will be complete
    is_complete: bool,
    /// Whether `?` and `[!...]` may match the delimiter character.
    ///
    /// When `true` (the user-facing default), `?` compiles to `.` and
    /// `[!abc]` compiles to `[^abc]` — both can match the delimiter,
    /// matching the historical (pre-strict) behavior.
    /// When `false`, both are restricted to a single segment by including
    /// the delimiter in their negated set.
    cross_delim: bool,
}

#[derive(Debug)]
pub(crate) struct PrefixSearchResult {
    pub prefixes: Vec<String>,
    pub objects: Vec<Object>,
    pub max_prefixes_observed: usize,
    pub max_objects_observed: usize,
}

/// A scanner takes a glob pattern and can efficiently generate a list of S3
/// prefixes based on it.
impl S3GlobMatcher {
    /// Parse a pattern.
    ///
    /// `cross_delim` controls whether `?` and negated character classes
    /// (`[!...]`) may match the delimiter character. Set `true` for the
    /// historical lax behavior, `false` for strict single-segment.
    pub fn parse(raw: String, delimiter: &str, cross_delim: bool) -> Result<Self> {
        let mut parts = Vec::new();
        let mut remaining = &*raw;
        while !remaining.is_empty() {
            let next_idx = remaining.find(GLOB_CHARS);
            match next_idx {
                Some(idx) => {
                    let next_part = remaining[..idx].to_string();
                    if !next_part.is_empty() {
                        parts.push(glob::Glob::Choice {
                            raw: next_part.clone(),
                            allowed: vec![next_part.clone()],
                        });
                    }
                    let gl = glob::parse_pattern(&remaining[idx..]).context("Parsing pattern")?;
                    remaining = &remaining[idx + gl.pattern_len()..];
                    parts.push(gl);
                }
                None => {
                    parts.push(glob::Glob::Choice {
                        raw: remaining.to_string(),
                        allowed: vec![remaining.to_string()],
                    });
                    break;
                }
            }
        }

        let mut new_parts: Vec<glob::Glob> = Vec::new();
        for part in parts {
            if let Some(last) = new_parts.last_mut() {
                if last.is_choice() && part.is_choice() {
                    last.combine_with(&part);
                } else {
                    new_parts.push(part);
                }
            } else {
                new_parts.push(part);
            }
        }
        if new_parts.last().is_some_and(|p| p.ends_with(delimiter)) {
            new_parts.push(glob::Glob::SyntheticAny);
        }

        debug!(pattern = %raw, parsed = ?new_parts, "parsed pattern");
        let is_complete = new_parts.iter().all(|p| !p.is_recursive());
        let regex = Regex::new(&Self::build_full_regex(
            &new_parts,
            delimiter.chars().next().unwrap(),
            cross_delim,
        ))
        .unwrap();
        Ok(S3GlobMatcher {
            raw,
            delimiter: delimiter.chars().next().unwrap(),
            parts: new_parts,
            regex,
            max_parallelism: 500,
            min_prefixes: DESIRED_MIN_PREFIXES,
            max_prefixes: MAX_PREFIXES,
            probe_max_keys: PROBE_MAX_KEYS,
            is_complete,
            cross_delim,
        })
    }

    // TODO: this should be a constructor argument, but I don't want to change
    // all the tests right now
    pub fn set_max_parallelism(&mut self, max_parallelism: usize) {
        self.max_parallelism = max_parallelism;
    }

    /// True if `key` matches this pattern's compiled regex.
    ///
    /// This is the brute-force oracle equivalent of the prefix-enumeration
    /// algorithm in [`Self::find_prefixes`]: it skips all the S3-listing
    /// optimizations and simply checks the key against the full pattern regex.
    #[cfg(test)]
    pub(crate) fn matches_key(&self, key: &str) -> bool {
        self.regex.is_match(key)
    }

    fn build_full_regex(parts: &[glob::Glob], delimiter: char, cross_delim: bool) -> String {
        let mut regex = "^".to_string();
        for (i, part) in parts.iter().enumerate() {
            // TODO: This is the existing behavior, should it be kept?
            // the delimiter is optional if the previous part is recursive, so **/*.txt is equivalent to **.txt
            if i > 0 && parts[i - 1].is_recursive() && part.is(&delimiter.to_string()) {
                regex.push(delimiter);
                regex.push('?');
            } else {
                regex.push_str(&part.re_string(&delimiter.to_string(), cross_delim));
            }
        }
        // prefixes end with the delimiter
        regex.push(delimiter);
        regex.push_str("?$");
        regex
    }

    /// Find all S3 prefixes that could match this pattern
    ///
    /// This method works by incrementally building up prefixes and filtering them based on
    /// the pattern parts:
    ///
    /// - For literal parts, it appends them to existing prefixes and queries S3 for matches
    /// - For pattern parts:
    ///   - `*` matches everything, but continues prefix generation
    ///   - `{a,b}` or `[ab]` either filters existing prefixes or generates new ones by appending each alternative
    ///   - `**` stops prefix generation (since it matches any number of path components)
    ///
    /// # Returns
    ///
    /// A list of S3 prefixes that could contain matches for this pattern
    ///
    /// # Example
    ///
    /// For pattern "foo/{bar,baz}*jook/qux*{alpha,beta}/**":
    /// 1. Start with [""]
    /// 2. Append "foo/" -> ["foo/"]
    /// 3. Append alternatives -> ["foo/bar", "foo/baz"]
    /// 4. Search for all folders in ["foo/bar", "foo/baz"]
    /// 4. Append "qux" -> ["foo/bar/qux", "foo/baz/qux"]
    /// 5. Filter by "*" -> keep prefixes whose last component starts with "qux"
    pub async fn find_prefixes(
        &self,
        mut engine: impl Engine + Clone,
    ) -> Result<PrefixSearchResult> {
        debug!("finding prefixes for {}", self.raw);
        let prefix_progress = progress::get().spinner(progress::prefix_spinner_style());
        let _prefix_cleanup = progress::ClearOnDrop(&prefix_progress);
        let mut prefixes = BTreeSet::new();
        prefixes.insert("".to_string());
        let mut objects: Vec<Object> = Vec::new();
        let mut objects_updated = false;
        let delimiter = self.delimiter.to_string();
        let mut regex_so_far = "^".to_string();
        let mut prev_part = None;
        let mut part_iter = self.parts.iter().enumerate();
        let mut max_prefixes_observed = 0;
        let mut max_objects_observed = 0;
        for (part_idx, part) in &mut part_iter {
            if prefixes.len() >= MAX_PREFIXES {
                warn!(
                    new_prefix_count = prefixes.len(),
                    "We have over {MAX_PREFIXES} prefixes, stopping prefix generation"
                );
                break;
            }
            max_prefixes_observed = max_prefixes_observed.max(prefixes.len());
            // only included prefixes in trace logs
            trace!(?prefixes, objects = ?objects.iter().map(|o| o.key().unwrap()).collect::<Vec<_>>(), "scanning for part");
            debug!(%regex_so_far, new_part = %part.re_string(&delimiter, self.cross_delim), prefix_count = prefixes.len(), object_count = objects.len(), "scanning for part");
            prefix_progress.set_position(prefixes.len() as u64);
            // We always want to scan for things including the last part,
            // finding more prefixes in it is guaranteed to be slower than
            // just searching because we have to do an api call to check each
            // prefix, instead of allowing aws to list them for us.
            match part {
                glob::Glob::Recursive => {
                    debug!("reached **, beginning bounded BFS expansion");
                    let initial = std::mem::take(&mut prefixes);
                    prefixes = self
                        .expand_recursive_frontier(
                            &engine,
                            &delimiter,
                            initial,
                            &mut objects,
                            &mut max_prefixes_observed,
                        )
                        .await?;
                    max_prefixes_observed = max_prefixes_observed.max(prefixes.len());
                    break;
                }
                // Any is the only place where we actually need to hit the
                // engine to scan for prefixes, everything else is either a
                // literal append or a regex filter
                glob::Glob::Any { .. } | glob::Glob::SyntheticAny => {
                    // never scan if the previous part was an any, because the last scan will have
                    // already found all of the prefixes that match the any
                    let scan_might_help = !matches!(prev_part, Some(&Glob::Any { .. }));
                    // might have no prefixes if we only found objects before any prefixes
                    if scan_might_help && !prefixes.is_empty() {
                        debug!(part = %part.display(), "scanning for keys in an Any");
                        let (tx, mut rx) = tokio::sync::mpsc::unbounded_channel();

                        let mut tasks = Vec::new();
                        let semaphore = Arc::new(Semaphore::new(self.max_parallelism));
                        for prefix in &prefixes {
                            let client_prefix = prefix.clone();
                            let delimiter = delimiter.clone();
                            let tx = tx.clone();
                            let permit = semaphore.clone().acquire_owned().await;
                            let mut engine = engine.clone();
                            let prefix = prefix.clone();
                            let regex = self.regex.clone();

                            let task = tokio::spawn(async move {
                                // if the prefix matches the regex, we can return it immediately
                                if !client_prefix.is_empty() && regex.is_match(&client_prefix) {
                                    tx.send(Ok((
                                        prefix.clone(),
                                        ScanResult::for_prefix(prefix.clone()),
                                    )))
                                    .expect("send to unbounded channel always works");
                                }
                                match engine.scan_prefixes(&client_prefix, &delimiter, None).await {
                                    Ok(results) => {
                                        let _ = tx.send(Ok((prefix, results)));
                                    }
                                    Err(e) => {
                                        let _ = tx.send(Err(e));
                                    }
                                }
                                drop(permit);
                            });
                            tasks.push(task);
                        }

                        drop(tx);

                        let mut new_prefixes = BTreeSet::new();
                        let mut new_prefix_count = 0;
                        while let Some(result) = rx.recv().await {
                            let (scanned_prefix, results) = result.context("scanning prefixes")?;
                            let result_len = results.len();
                            trace!(
                                scanned_prefix,
                                scanned_results_count = result_len,
                                scanned_results = ?results,
                                "Scanning for any, got result from task"
                            );
                            new_prefixes.extend(results.prefixes);
                            if !objects_updated {
                                objects_updated = !results.objects.is_empty();
                            }
                            objects
                                .extend(results.objects.into_iter().filter(|o| self.match_obj(o)));
                            new_prefix_count = new_prefixes.len();
                            if new_prefix_count >= MAX_PREFIXES {
                                debug!(
                                    new_prefix_count,
                                    "Scanning for any, found more than {MAX_PREFIXES} prefixes, aborting"
                                );
                                for task in tasks {
                                    task.abort();
                                }
                                break;
                            }
                        }
                        // don't overwrite if we gave up early, we'll break at the top of the loop
                        if new_prefix_count < MAX_PREFIXES {
                            prefixes = new_prefixes;
                        }
                    }
                    max_objects_observed = max_objects_observed.max(prefixes.len());
                    if part.is_negated() {
                        // if this part is a negated character class then we should filter
                        let matcher = Regex::new(&format!(
                            "{regex_so_far}{}",
                            part.re_string(&self.delimiter.to_string(), self.cross_delim)
                        ))
                        .unwrap();
                        debug!(regex = %matcher.as_str(), "filtering for negated Any");
                        prefixes.retain(|p| matcher.is_match(p));
                    }
                }
                glob::Glob::Choice { allowed, .. } => {
                    // In an alternation we need to check for two cases:
                    // - we are verifying that the middle of the path matches
                    //   one of the alternatives -- this is just a regex filter
                    //
                    //   This happens when the previous part does _not_
                    //   with the delimiter.
                    //
                    // - we are constructing a new path component from the list of alternaives,
                    //   where we just join each alternative with the
                    //   delimiter.
                    //
                    //   This happens when the previous part ended with
                    //   the delimiter, or the pattern starts with an
                    //   alternation

                    // if there is no previous part
                    let is_simple_append = part_idx == 0;

                    if is_simple_append {
                        debug!(allowed = %allowed.join(","), "simple append");
                        let mut new_prefixes = BTreeSet::new();
                        for prefix in &prefixes {
                            for alt in allowed {
                                new_prefixes.insert(prefix_join(prefix, alt));
                            }
                        }
                        if new_prefixes.len() >= MAX_CHECK_PREFIXES {
                            debug!(
                                new_prefix_count = new_prefixes.len(),
                                "simple append generated over {MAX_CHECK_PREFIXES} prefixes, using prefixes from previous part"
                            );
                            break;
                        }
                        max_objects_observed = max_objects_observed.max(new_prefixes.len());
                        prefixes = check_prefixes(
                            &mut engine,
                            &prefixes,
                            new_prefixes,
                            self.max_parallelism,
                        )
                        .await?;
                    } else {
                        // Build up the filters and appends
                        let mut filters = BTreeSet::new();
                        let mut appends = BTreeSet::new();
                        for choice in allowed {
                            // the last part is guaranteed to be an Any,
                            if choice.starts_with(self.delimiter) {
                                let c = choice.chars().skip(1).collect::<String>();
                                if !c.is_empty() {
                                    appends.insert(c);
                                }
                                filters.insert(self.delimiter.to_string());
                            } else if choice.contains(self.delimiter) {
                                let up_to_delim = choice
                                    .chars()
                                    .take_while_inclusive(|c| *c != self.delimiter)
                                    .collect::<String>();
                                filters.insert(regex::escape(&up_to_delim));

                                let after_delim = choice[up_to_delim.len()..].to_string();
                                if !after_delim.is_empty() {
                                    appends.insert(after_delim);
                                }
                            } else {
                                filters.insert(regex::escape(choice));
                            }
                        }

                        let filter = if filters.is_empty() {
                            Regex::new(&regex_so_far).unwrap()
                        } else if filters.len() == 1 {
                            Regex::new(&format!(
                                "{}{}",
                                regex_so_far,
                                filters.iter().next().unwrap()
                            ))
                            .unwrap()
                        } else {
                            let filters = filters.iter().join("|");
                            Regex::new(&format!("{}({})", regex_so_far.as_str(), filters)).unwrap()
                        };
                        let append_matcher = Regex::new(&format!(
                            "{}{}",
                            regex_so_far,
                            part.re_string(&delimiter, self.cross_delim)
                        ))
                        .unwrap();
                        trace!(
                            ?filters, ?appends, filter_regex = %filter.as_str(), append_regex = %append_matcher.as_str(), ?prefixes,
                            "filtering and appending to prefixes",
                        );

                        let new_prefixes = if filters.is_empty() {
                            debug!("no filters, appending");
                            let mut new_prefixes = BTreeSet::new();
                            for prefix in &prefixes {
                                for alt in &appends {
                                    new_prefixes.insert(prefix_join(prefix, alt));
                                }
                            }
                            new_prefixes
                        } else if appends.is_empty() {
                            debug!("no appends, filtering");
                            let mut new_prefixes = BTreeSet::new();
                            for prefix in &prefixes {
                                if filter.is_match(prefix) {
                                    new_prefixes.insert(prefix.clone());
                                }
                            }
                            new_prefixes
                        } else {
                            debug!("filtering and appending");
                            let mut new_prefixes = BTreeSet::new();
                            for prefix in &prefixes {
                                if filter.is_match(prefix) {
                                    // Keep the prefix as-is if it already
                                    // matches the appended-form regex. We
                                    // *also* try appending each alt: when the
                                    // alt set includes both a delim-only alt
                                    // (which the prefix satisfies via the
                                    // empty-after-delim path) and other alts
                                    // that add real content, the additional
                                    // appends surface keys the empty-alt path
                                    // would otherwise miss (e.g. `*{,:b}`
                                    // against `["a:b"]`).
                                    if append_matcher.is_match(prefix) {
                                        new_prefixes.insert(prefix.clone());
                                    }
                                    for alt in &appends {
                                        new_prefixes.insert(prefix_join(prefix, alt));
                                    }
                                }
                            }
                            trace!(?new_prefixes, "filtered and appended prefixes");
                            new_prefixes
                        };

                        if !appends.is_empty() {
                            debug!("validating appends and filters");
                            if new_prefixes.len() >= MAX_PREFIXES {
                                // checking prefixes is significantly slower
                                // than scanning existing prefixes.
                                debug!(
                                    new_prefix_count = new_prefixes.len(),
                                    "Appends generated over {MAX_PREFIXES} prefixes, using prefixes from previous part"
                                );
                                break;
                            }
                            trace!(new_prefixes = ?new_prefixes, new_prefix_count = new_prefixes.len(), "checking appended prefixes");
                            max_objects_observed = max_objects_observed.max(new_prefixes.len());
                            let new_prefixes = check_prefixes(
                                &mut engine,
                                &prefixes,
                                new_prefixes,
                                self.max_parallelism,
                            )
                            .await?;
                            if new_prefixes.is_empty() {
                                if objects.is_empty() {
                                    debug!("no prefixes matched and no objects exist");
                                    prefixes.clear();
                                    break;
                                }
                                // keep prior prefixes — we already have matched objects
                            } else {
                                prefixes = new_prefixes;
                            }
                        } else if !new_prefixes.is_empty() {
                            debug!("no appends, using new prefixes");
                            prefixes = new_prefixes;
                        } else {
                            debug!("everything was filtered out");
                            let glob_so_far = self
                                .parts
                                .iter()
                                .take(part_idx + 1)
                                .map(|p| p.raw())
                                .join("");
                            let max_prefixes = if tracing::enabled!(tracing::Level::DEBUG) {
                                usize::MAX
                            } else {
                                20
                            };
                            let and_more = if prefixes.len() > max_prefixes {
                                format!(
                                    "\n  ...and {} more (run with --verbose to see all)",
                                    prefixes.len() - max_prefixes
                                )
                            } else {
                                String::new()
                            };

                            if !objects_updated || objects.is_empty() {
                                let debug_prefixes =
                                    prefixes.iter().take(max_prefixes).join("\n  ");
                                progressln!(
                                    "Could not continue search in prefixes:\n  {}{}\
                                \n\n\
                                None of the above matched the pattern:\n  {glob_so_far}",
                                    debug_prefixes,
                                    and_more,
                                );
                                prefixes.clear();
                                break;
                            } else {
                                objects_updated = false;
                            }
                        }
                    }
                }
            }

            // clean up state-tracking
            regex_so_far = format!(
                "{}{}",
                regex_so_far.as_str(),
                part.re_string(&self.delimiter.to_string(), self.cross_delim)
            );

            prev_part = Some(part);
        }

        let count = prefixes.len();
        if count < self.min_prefixes && !self.is_complete {
            progressln!(
                "Discovered prefixes: {count:>5} -- see `s3glob help parallelism` if it feels like this run is too slow"
            );
        } else {
            let noun = if self.is_complete {
                "matches"
            } else {
                "prefixes"
            };
            progressln!("Discovered {noun}: {count:>5}");
        }
        // For complete patterns, every prefix in the final result must
        // match the full regex (including the trailing `[delim]?$`). The
        // Any handler scans subprefixes and adds them all without
        // verifying, this is the last place we check.
        if self.is_complete {
            prefixes.retain(|p| self.regex.is_match(p));
        }
        Ok(PrefixSearchResult {
            prefixes: prefixes.into_iter().collect(),
            objects,
            max_prefixes_observed,
            max_objects_observed,
        })
    }

    pub(crate) async fn get_objects<E: Engine + Clone>(&self, engine: E) -> Result<ListResult> {
        let presult = self.find_prefixes(engine.clone()).await?;
        trace!(?presult.prefixes, "matcher generated prefixes");
        debug!(
            prefix_count = presult.prefixes.len(),
            "matcher generated prefixes"
        );
        let max_objects_observed = presult.max_objects_observed;
        let max_prefixes_observed = presult.max_prefixes_observed;
        let status = LiveStatus {
            total_objects: Arc::new(AtomicUsize::new(0)),
            seen_prefixes: Arc::new(AtomicUsize::new(0)),
        };
        let total_prefixes = presult.prefixes.len();
        let (tx, rx) = tokio::sync::mpsc::unbounded_channel::<Vec<PrefixResult>>();
        let re = self.regex.clone();
        debug!(regex = %re.as_str(), "full regex");
        if self.is_complete() {
            let permit = Arc::new(Semaphore::new(self.max_parallelism));
            engine
                .get_exact(presult, self.delimiter, &status, &re, &tx, permit)
                .await?;
        } else {
            let permit = Arc::new(Semaphore::new(self.max_parallelism));
            engine
                .get_all_children(presult, Arc::new(re), &status, &tx, permit)
                .await?;
        }
        drop(tx);
        Ok(ListResult {
            totals: Totals {
                max_objects_observed,
                max_prefixes_observed,
                total_prefixes,
            },
            status,
            rx,
        })
    }

    /// True if no further listing needs to be done by the caller
    pub fn is_complete(&self) -> bool {
        self.is_complete
    }

    /// True if `obj`'s key matches the full compiled regex.
    fn match_obj(&self, obj: &Object) -> bool {
        obj.key.as_ref().is_some_and(|key| self.regex.is_match(key))
    }

    /// Bounded BFS prefix expansion at a `**` glob component.
    ///
    /// Expands `initial` one directory level at a time until we reach
    /// `min_prefixes`, exhaust the frontier, or hit `max_prefixes`.
    /// Returns the final settled-plus-frontier set; any objects
    /// resolved along the way are appended to `objects`.
    ///
    /// Each round runs two phases per frontier prefix:
    ///   1. Probe with a single delimiter-less LIST (max_keys =
    ///      probe_max_keys). Non-truncated probes mean the prefix's
    ///      full content fits in one call; matching keys go to
    ///      `objects` and the prefix is dropped. Truncated probes
    ///      queue the prefix for phase 2.
    ///   2. Scan with delimiter and a max-prefixes cap. Truncated
    ///      scans (cap hit or flat-dense parent) settle the parent
    ///      for `get_all_children`. Leaf scans (truncated=false, no
    ///      sub-prefixes) forward their complete content like phase 1
    ///      and drop the prefix. Branch scans replace the parent
    ///      with sub-prefixes and carry direct objects forward.
    async fn expand_recursive_frontier<E: Engine + Clone>(
        &self,
        engine: &E,
        delimiter: &str,
        initial: BTreeSet<String>,
        objects: &mut Vec<Object>,
        max_prefixes_observed: &mut usize,
    ) -> Result<BTreeSet<String>> {
        let probe_max_keys = self.probe_max_keys;
        let mut settled: BTreeSet<String> = BTreeSet::new();
        let mut frontier = initial;

        while settled.len() + frontier.len() < self.min_prefixes && !frontier.is_empty() {
            debug!(
                settled_count = settled.len(),
                frontier_count = frontier.len(),
                min_prefixes = self.min_prefixes,
                "too few prefixes at **, expanding one directory level"
            );

            // Phase 1: parallel probe of the frontier.
            let probe_results = {
                let engine = engine.clone();
                fan_out_per_prefix(&frontier, self.max_parallelism, move |prefix| {
                    let mut engine = engine.clone();
                    async move { engine.probe_prefix(&prefix, probe_max_keys).await }
                })
                .await
            };

            let mut to_scan = BTreeSet::new();
            for (prefix, result) in probe_results {
                let probe = result.context("probing prefix at **")?;
                if probe.truncated {
                    to_scan.insert(prefix);
                } else {
                    // Sparse prefix: probe returned complete content.
                    objects.extend(probe.objects.into_iter().filter(|o| self.match_obj(o)));
                }
            }

            if to_scan.is_empty() {
                debug!("all frontier prefixes resolved by probe, stopping");
                frontier.clear();
                break;
            }

            // Phase 2: capped delimiter-aware scan of the dense prefixes.
            let scan_cap = self.max_parallelism;
            let scan_results = {
                let engine = engine.clone();
                let delimiter = delimiter.to_string();
                fan_out_per_prefix(&to_scan, self.max_parallelism, move |prefix| {
                    let mut engine = engine.clone();
                    let delimiter = delimiter.clone();
                    async move {
                        engine
                            .scan_prefixes(&prefix, &delimiter, Some(scan_cap))
                            .await
                    }
                })
                .await
            };

            let mut new_frontier = BTreeSet::new();
            let mut made_progress = false;
            for (prefix, result) in scan_results {
                let scan_result = result.context("expanding prefixes at **")?;
                if scan_result.truncated {
                    // Cap hit (too wide) or page-budget exhausted
                    // looking for non-existent sub-prefixes. Either
                    // way, parallel expansion isn't worth it; hand the
                    // parent to get_all_children.
                    debug!(
                        %prefix,
                        sub_prefix_count = scan_result.prefixes.len(),
                        "scan truncated, falling back to parent listing"
                    );
                    settled.insert(prefix);
                } else if scan_result.prefixes.is_empty() {
                    // True leaf with complete content: forward objects
                    // like the probe-resolved sparse path, skipping
                    // the get_all_children re-list entirely.
                    objects.extend(
                        scan_result
                            .objects
                            .into_iter()
                            .filter(|o| self.match_obj(o)),
                    );
                } else {
                    made_progress = true;
                    new_frontier.extend(scan_result.prefixes);
                    // Direct objects at a branch prefix would be lost
                    // when we drop the parent in favor of its children.
                    // Carry them forward.
                    objects.extend(
                        scan_result
                            .objects
                            .into_iter()
                            .filter(|o| self.match_obj(o)),
                    );
                }
            }

            if !made_progress {
                debug!("no sub-directories found during ** expansion, stopping");
                frontier.clear();
                break;
            }

            let total_after = settled.len() + new_frontier.len();
            *max_prefixes_observed = (*max_prefixes_observed).max(total_after);

            if total_after >= self.max_prefixes {
                let cap = self.max_prefixes;
                warn!(
                    new_prefix_count = total_after,
                    "found over {cap} prefixes during ** expansion, stopping"
                );
                frontier = new_frontier;
                break;
            }

            frontier = new_frontier;
        }

        Ok(settled.into_iter().chain(frontier).collect())
    }

    /// Set the BFS target prefix count at `**`.
    ///
    /// The expansion loop runs while `settled + frontier < min_prefixes`.
    /// Setting this to `0` (or any value the initial frontier already
    /// exceeds) skips the loop entirely, so the `**` falls straight
    /// through to a single-prefix recursive listing in
    /// `get_all_children`.
    pub fn set_min_prefixes(&mut self, min_prefixes: usize) {
        self.min_prefixes = min_prefixes;
    }

    #[cfg(test)]
    fn set_probe_max_keys(&mut self, probe_max_keys: i32) {
        self.probe_max_keys = probe_max_keys;
    }

    #[cfg(test)]
    fn set_max_prefixes(&mut self, max_prefixes: usize) {
        self.max_prefixes = max_prefixes;
    }
}

/// Run `make` over each prefix in parallel, bounded by
/// `max_parallelism`, and return one `(prefix, Result)` per input.
///
/// `make` is called once per prefix with the owned `String` and must
/// produce a `Send + 'static` future — the helper does the
/// `tokio::spawn` and `Semaphore`-bounded channel collection.
async fn fan_out_per_prefix<T, F, Fut>(
    prefixes: &BTreeSet<String>,
    max_parallelism: usize,
    mut make: F,
) -> Vec<(String, Result<T>)>
where
    F: FnMut(String) -> Fut,
    Fut: std::future::Future<Output = Result<T>> + Send + 'static,
    T: Send + 'static,
{
    if prefixes.is_empty() {
        return Vec::new();
    }
    let (tx, mut rx) = tokio::sync::mpsc::channel(prefixes.len());
    let semaphore = Arc::new(Semaphore::new(max_parallelism));
    for prefix in prefixes {
        let prefix = prefix.clone();
        let tx = tx.clone();
        let permit = semaphore.clone().acquire_owned().await;
        let fut = make(prefix.clone());
        tokio::spawn(async move {
            let result = fut.await;
            drop(permit);
            let _ = tx.send((prefix, result)).await;
        });
    }
    drop(tx);
    let mut out = Vec::with_capacity(prefixes.len());
    while let Some(item) = rx.recv().await {
        out.push(item);
    }
    out
}

async fn check_prefixes(
    engine: &mut (impl Engine + Clone),
    prefixes: &BTreeSet<String>,
    new_prefixes: BTreeSet<String>,
    max_parallelism: usize,
) -> Result<BTreeSet<String>, anyhow::Error> {
    if prefixes.is_empty() || new_prefixes.is_empty() {
        debug!("check_prefixes called with no prefixes to build off of or none to check");
        return Ok(BTreeSet::new());
    }
    let checked_prefixes = engine
        .check_prefixes(new_prefixes.clone(), max_parallelism)
        .await?;
    if checked_prefixes.is_empty() {
        let mut message = vec!["Searched for prefixes do not exist in the bucket:".to_string()];
        let new_prefixes = new_prefixes.iter().collect::<Vec<_>>();
        let mut new_idx = 0;
        for prefix in prefixes {
            message.push(format!("  {}", prefix));
            let mut new_prefix = new_prefixes.get(new_idx);
            while new_prefix.is_some()
                && &prefix <= new_prefix.unwrap()
                && new_prefix.unwrap().starts_with(prefix)
            {
                message.push(format!(
                    "    INVALID: {}",
                    &new_prefixes[new_idx][prefix.len()..]
                ));
                new_idx += 1;
                new_prefix = new_prefixes.get(new_idx);
            }
        }

        progressln!("{}", message.join("\n"));
    }
    Ok(checked_prefixes)
}

fn prefix_join(prefix: &str, alt: &str) -> String {
    format!("{prefix}{alt}")
}
// Final listing code

#[derive(Debug)]
pub(crate) enum PrefixResult {
    Object(S3Object),
    Prefix(String),
}

impl PrefixResult {
    pub(crate) fn kind(&self) -> String {
        match self {
            Self::Object(_) => "OBJ".to_owned(),
            Self::Prefix(_) => "PRE".to_owned(),
        }
    }
    pub(crate) fn key(&self) -> String {
        match self {
            Self::Object(obj) => obj.key.clone(),
            Self::Prefix(prefix) => prefix.clone(),
        }
    }
}

pub(crate) struct ListResult {
    pub(crate) status: LiveStatus,
    pub(crate) totals: Totals,
    pub(crate) rx: UnboundedReceiver<Vec<PrefixResult>>,
}

pub(crate) struct Totals {
    pub(crate) total_prefixes: usize,
    pub(crate) max_objects_observed: usize,
    pub(crate) max_prefixes_observed: usize,
}

pub(crate) struct LiveStatus {
    pub(crate) total_objects: Arc<AtomicUsize>,
    pub(crate) seen_prefixes: Arc<AtomicUsize>,
}

#[cfg(test)]
mod tests {
    use assert2::{assert, check};

    use super::*;
    use crate::glob_matcher::engine::MockS3Engine;
    use crate::{assert_scanner_part, setup_logging};
    use tracing::info;

    //
    // find_prefixes tests
    //

    #[tokio::test]
    async fn test_find_prefixes_literal() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("src/foo/bar".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        let engine = MockS3Engine::new(vec!["src/foo/bar".to_string()]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        assert!(prefixes == vec!["src/foo/bar"]);
        let e: &[(&str, &str)] = &[];
        engine.assert_calls(e);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_alternation_no_any() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("src/{foo,bar}/baz".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        let engine = MockS3Engine::new(vec![
            "src/foo/baz".to_string(),
            "src/bar/baz".to_string(),
            "src/qux/baz".to_string(), // Should be filtered out
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        assert!(prefixes == vec!["src/bar/baz", "src/foo/baz"]);
        let e: &[(&str, &str)] = &[];
        engine.assert_calls(e);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_alternation_with_any() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("src/{foo,bar}*/baz".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        println!("scanner_parts for {}:\n{:?}", scanner.raw, scanner.parts);
        let engine = MockS3Engine::new(vec![
            "src/foo/baz".to_string(),
            "src/bar/baz".to_string(),
            "src/foo-quux/baz".to_string(),
            "src/qux/baz".to_string(), // Should be filtered out
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        engine.assert_calls(&[("src/bar", "/"), ("src/foo", "/")]);
        assert!(prefixes == vec!["src/bar/baz", "src/foo-quux/baz", "src/foo/baz"]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_star() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("src/*/main.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        let engine = MockS3Engine::new(vec![
            "src/foo/main.rs".to_string(),
            "src/bar/main.rs".to_string(),
            "src/baz/other.rs".to_string(),
        ]);
        info!(?engine.paths);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        assert!(prefixes == vec!["src/bar/main.rs", "src/foo/main.rs"]);
        engine.assert_calls(&[("src/", "/")]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_recursive() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("src/**/test.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        let engine = MockS3Engine::new(vec![
            "src/test.rs".to_string(),
            "src/foo/test.rs".to_string(),
            "src/foo/bar/test.rs".to_string(),
            "src/other.rs".to_string(),
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        // Should stop at src/ since ** matches anything after
        assert!(prefixes == vec!["src/"]);
        let e: &[(&str, &str)] = &[];
        engine.assert_calls(e);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_recursive_expands_when_few_prefixes() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("src/**/*.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(3);
        // Force the scan path: pretend the probe always says "more exists"
        // so we drop to delimiter-aware enumeration.
        scanner.set_probe_max_keys(1);
        let engine = MockS3Engine::new(vec![
            "src/bar/test.rs".to_string(),
            "src/baz/test.rs".to_string(),
            "src/foo/test.rs".to_string(),
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        // src/ has 3 sub-dirs: bar/, baz/, foo/ — one expansion round reaches min_prefixes
        assert!(prefixes == vec!["src/bar/", "src/baz/", "src/foo/"]);
        engine.assert_calls(&[("src/", "/")]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_recursive_expands_multiple_levels() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("src/**/*.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(3);
        scanner.set_probe_max_keys(1);
        // src/ has only one sub-dir; a second level is needed to reach min_prefixes
        let engine = MockS3Engine::new(vec![
            "src/foo/a/test.rs".to_string(),
            "src/foo/b/test.rs".to_string(),
            "src/foo/c/test.rs".to_string(),
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        // Round 1: src/ → src/foo/ (1 prefix < 3)
        // Round 2: src/foo/ → src/foo/a/, src/foo/b/, src/foo/c/ (3 prefixes >= 3)
        assert!(prefixes == vec!["src/foo/a/", "src/foo/b/", "src/foo/c/"]);
        engine.assert_calls(&[("src/", "/"), ("src/foo/", "/")]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_recursive_forwards_leaf_objects() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        // When a scan returns `truncated=false` with no sub-prefixes
        // the scan already paged through the leaf's complete content.
        // The BFS forwards those objects directly (mirroring the
        // probe-resolved sparse path) and drops the prefix — no need
        // for `get_all_children` to re-list it. This saves one API
        // call per leaf in production.
        let mut scanner = S3GlobMatcher::parse("src/**/*.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(3);
        // probe_max_keys=1 forces every prefix's probe to truncate, so
        // leaf classification comes from the scan arm (not probe).
        scanner.set_probe_max_keys(1);
        let paths = vec![
            "src/bar/a/one.rs".to_string(),
            "src/bar/a/two.rs".to_string(),
            "src/foo/one.rs".to_string(),
            "src/foo/two.rs".to_string(),
        ];
        let engine = MockS3Engine::new(paths.clone());

        let presult = scanner.find_prefixes(engine.clone()).await?;
        // Round 1: scan(src/) → branch into {src/bar/, src/foo/}.
        // Round 2: scan(src/bar/) → branch (src/bar/a/);
        //          scan(src/foo/) → leaf → forward two .rs files.
        // Round 3: scan(src/bar/a/) → leaf → forward two .rs files.
        // Final: presult.prefixes empty; presult.objects has all four.
        assert!(
            presult.prefixes.is_empty(),
            "leaf forwarding should empty the prefix set, got: {:?}",
            presult.prefixes,
        );
        let mut object_keys: Vec<String> = presult
            .objects
            .iter()
            .filter_map(|o| o.key.clone())
            .collect();
        object_keys.sort();
        let mut expected = paths.clone();
        expected.sort();
        assert!(
            object_keys == expected,
            "expected all four matching keys forwarded;\n  got:      {object_keys:?}\n  expected: {expected:?}",
        );
        // Round 2 spawns scan(src/bar/) and scan(src/foo/) in parallel,
        // so their relative order is non-deterministic.
        engine.assert_call_set(&[
            ("src/", "/"),
            ("src/bar/", "/"),
            ("src/foo/", "/"),
            ("src/bar/a/", "/"),
        ]);

        // End-to-end: with prefixes empty, `get_all_children` does no
        // listing work and just forwards the already-collected objects.
        // Each matching key is emitted exactly once.
        let mut result = scanner
            .get_objects(MockS3Engine::new(paths.clone()))
            .await?;
        let mut keys: Vec<String> = Vec::new();
        while let Some(batch) = result.rx.recv().await {
            for r in batch {
                if let PrefixResult::Object(obj) = r {
                    keys.push(obj.key);
                }
            }
        }
        keys.sort();
        assert!(
            keys == expected,
            "expected each matching key emitted once via leaf forwarding;\n  got:      {keys:?}\n  expected: {expected:?}",
        );
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_recursive_no_expansion_when_enough_prefixes() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        // Start with multiple prefixes before ** — no expansion needed
        let mut scanner = S3GlobMatcher::parse("{a,b,c}/**/*.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(3);
        let engine = MockS3Engine::new(vec![
            "a/test.rs".to_string(),
            "b/test.rs".to_string(),
            "c/test.rs".to_string(),
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        // Already 3 prefixes (a/, b/, c/) — no expansion calls needed
        assert!(prefixes == vec!["a/", "b/", "c/"]);
        // check_prefixes is called (for the Choice part), but no scan_prefixes for **
        let calls = engine.calls.lock().unwrap();
        assert!(
            calls.is_empty(),
            "expected no scan_prefixes calls, got: {calls:?}"
        );
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_recursive_resolves_sparse_via_probe() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        // Default probe_max_keys=1000 — small bucket fits in one probe call,
        // no scan is needed.
        let mut scanner = S3GlobMatcher::parse("src/**/*.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(25);
        let engine = MockS3Engine::new(vec![
            "src/bar/test.rs".to_string(),
            "src/foo/test.rs".to_string(),
        ]);

        let presult = scanner.find_prefixes(engine.clone()).await?;
        // Probe returned 2 keys, not truncated → both resolved directly.
        assert!(presult.prefixes.is_empty());
        let object_keys: Vec<String> = presult
            .objects
            .iter()
            .filter_map(|o| o.key.clone())
            .collect();
        assert!(object_keys.contains(&"src/bar/test.rs".to_string()));
        assert!(object_keys.contains(&"src/foo/test.rs".to_string()));
        // No delimiter-aware scan was needed.
        let scan_calls = engine.calls.lock().unwrap();
        assert!(
            scan_calls.is_empty(),
            "expected no scan_prefixes calls, got: {scan_calls:?}"
        );
        Ok(())
    }

    #[tokio::test]
    async fn test_get_objects_recursive_forwards_probe_resolved_objects() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        // Regression guard: when the probe phase at `**` resolves a sparse
        // prefix in one call, matching keys are stashed in `presult.objects`
        // and the prefix is dropped from the frontier. `get_all_children`
        // must forward those objects to the output channel — if it ever
        // stops doing so, sparse `**` queries silently return zero matches.
        let scanner = S3GlobMatcher::parse("src/**/*.rs".to_string(), "/", false)?;
        let engine = MockS3Engine::new(vec![
            "src/bar/test.rs".to_string(),
            "src/foo/sub/deep.rs".to_string(),
            "src/foo/test.rs".to_string(),
            // non-matching key under the same prefix; must NOT appear
            "src/skip.txt".to_string(),
        ]);

        let mut result = scanner.get_objects(engine).await?;

        let mut keys: Vec<String> = Vec::new();
        while let Some(batch) = result.rx.recv().await {
            for r in batch {
                if let PrefixResult::Object(obj) = r {
                    keys.push(obj.key);
                }
            }
        }
        keys.sort();

        assert!(
            keys == vec![
                "src/bar/test.rs".to_string(),
                "src/foo/sub/deep.rs".to_string(),
                "src/foo/test.rs".to_string(),
            ],
            "expected probe-resolved objects forwarded to channel, got: {keys:?}",
        );
        Ok(())
    }

    #[tokio::test]
    async fn test_get_objects_recursive_no_duplicate_emissions_with_mixed_outcomes() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        // Regression guard: across rounds of `**` expansion with mixed
        // leaf/branch/truncated outcomes, the final prefix set must
        // not contain both an ancestor and one of its descendants —
        // otherwise `get_all_children` would double-list everything
        // under the descendant.
        //
        // Scenario: `{a,b,c}/**/*.rs` pre-populates the initial frontier
        // with three sibling prefixes so we exercise the BFS without
        // depending on round-1 src/ scan behavior. With probe_max_keys=1
        // and ≥2 keys per prefix every probe truncates; cap=3 so:
        //   Round 1: a/ → leaf (forward 2 objects);
        //            b/ → 1 sub-dir (branch, new_frontier += b/x/);
        //            c/ → 4 sub-dirs (> cap) → truncated (settled).
        //   Round 2: b/x/ → leaf (forward 2 objects); break.
        //   Final: settled={c/}, objects=[a/*, b/x/*]. Only c/ remains
        //   in prefixes — neither it nor its descendants overlap with
        //   anything else in the result.
        let mut scanner = S3GlobMatcher::parse("{a,b,c}/**/*.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(10);
        scanner.set_probe_max_keys(1);
        scanner.set_max_parallelism(3);

        let paths = vec![
            "a/file1.rs".to_string(),
            "a/file2.rs".to_string(),
            "b/x/file1.rs".to_string(),
            "b/x/file2.rs".to_string(),
            "c/p/f.rs".to_string(),
            "c/q/f.rs".to_string(),
            "c/r/f.rs".to_string(),
            "c/s/f.rs".to_string(),
        ];

        // Sanity: the scenario actually exercised mixed BFS outcomes
        // — the truncated parent c/ stays in prefixes, the leaves go
        // to objects.
        let presult = scanner
            .find_prefixes(MockS3Engine::new(paths.clone()))
            .await?;
        assert!(
            presult.prefixes == vec!["c/".to_string()],
            "expected only the truncated parent in prefixes, got: {:?}",
            presult.prefixes,
        );
        let mut object_keys: Vec<String> = presult
            .objects
            .iter()
            .filter_map(|o| o.key.clone())
            .collect();
        object_keys.sort();
        assert!(
            object_keys
                == vec![
                    "a/file1.rs".to_string(),
                    "a/file2.rs".to_string(),
                    "b/x/file1.rs".to_string(),
                    "b/x/file2.rs".to_string(),
                ],
            "expected leaf-forwarded objects from a/ and b/x/, got: {object_keys:?}",
        );

        // Invariant 1: no element of presult.prefixes is a strict
        // prefix of another. presult.prefixes is sorted, so consecutive
        // pairs suffice — any X that is a strict prefix of any Y is
        // adjacent to *some* Y' it strictly precedes.
        for window in presult.prefixes.windows(2) {
            let (a, b) = (&window[0], &window[1]);
            assert!(
                !(a != b && b.starts_with(a.as_str())),
                "prefix {a:?} is a strict ancestor of {b:?} in {:?}",
                presult.prefixes,
            );
        }

        // Invariant 2: get_objects emits each matching key exactly
        // once. A bug that admitted overlapping prefixes would surface
        // here as duplicate emissions even if invariant 1 missed it.
        let mut result = scanner
            .get_objects(MockS3Engine::new(paths.clone()))
            .await?;
        let mut keys: Vec<String> = Vec::new();
        while let Some(batch) = result.rx.recv().await {
            for r in batch {
                if let PrefixResult::Object(obj) = r {
                    keys.push(obj.key);
                }
            }
        }
        keys.sort();

        let mut expected = paths;
        expected.sort();
        assert!(
            keys == expected,
            "expected each matching key emitted exactly once;\n  got:      {keys:?}\n  expected: {expected:?}",
        );
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_recursive_falls_back_when_scan_capped() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        // 5 sub-dirs but max_parallelism=2 caps the scan. The mock
        // returns truncated when sub-prefix count exceeds the cap, which
        // triggers the parent-fallback path: the original prefix stays
        // in the final set instead of being replaced by partial children.
        let mut scanner = S3GlobMatcher::parse("src/**/*.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(25);
        scanner.set_probe_max_keys(1);
        scanner.set_max_parallelism(2);
        let engine = MockS3Engine::new(vec![
            "src/a/x.rs".to_string(),
            "src/b/x.rs".to_string(),
            "src/c/x.rs".to_string(),
            "src/d/x.rs".to_string(),
            "src/e/x.rs".to_string(),
        ]);

        let presult = scanner.find_prefixes(engine.clone()).await?;
        assert!(
            presult.prefixes == vec!["src/"],
            "expected fallback to parent, got prefixes={:?}",
            presult.prefixes,
        );
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_recursive_keeps_branch_direct_objects() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        // src/foo/ is a *branch*: it has a sub-dir (src/foo/sub/) AND a direct
        // file (src/foo/bar.rs). Both files match `src/**/*.rs`, so neither
        // may be lost when expansion replaces src/foo/ with src/foo/sub/.
        let mut scanner = S3GlobMatcher::parse("src/**/*.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(3);
        // Force scan path so we exercise the branch-direct-object case
        // instead of letting the probe resolve everything.
        scanner.set_probe_max_keys(1);
        let paths = vec![
            "src/foo/bar.rs".to_string(),
            "src/foo/sub/baz.rs".to_string(),
        ];

        let presult = scanner
            .find_prefixes(MockS3Engine::new(paths.clone()))
            .await?;

        // After expansion, src/foo/ is replaced by src/foo/sub/. For
        // src/foo/bar.rs to remain reachable end-to-end, it must be carried
        // forward in presult.objects (mirroring what the Any arm does).
        let object_keys: Vec<String> = presult
            .objects
            .iter()
            .filter_map(|o| o.key.clone())
            .collect();
        assert!(
            object_keys.iter().any(|k| k == "src/foo/bar.rs"),
            "expected src/foo/bar.rs in presult.objects, prefixes={:?} objects={:?}",
            presult.prefixes,
            object_keys,
        );
        // End-to-end check: both files reachable, neither emitted twice.
        // This is what the test name actually claims — "neither file
        // is lost". Whether src/foo/sub/baz.rs comes through via a
        // covering prefix or via probe-resolved objects depends on the
        // BFS scheduling; either path is correct, but neither file may
        // be missing or duplicated in the output.
        let mut result = scanner
            .get_objects(MockS3Engine::new(paths.clone()))
            .await?;
        let mut keys: Vec<String> = Vec::new();
        while let Some(batch) = result.rx.recv().await {
            for r in batch {
                if let PrefixResult::Object(obj) = r {
                    keys.push(obj.key);
                }
            }
        }
        keys.sort();
        let mut expected = paths;
        expected.sort();
        assert!(
            keys == expected,
            "expected both files emitted exactly once;\n  got:      {keys:?}\n  expected: {expected:?}",
        );
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_recursive_stops_at_max_prefixes() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        // The BFS has a hard cap (`max_prefixes`) that aborts expansion
        // once total prefixes (settled + new_frontier) reach it. Without
        // a test, off-by-one or "forgot to seed `frontier = new_frontier`
        // before break" regressions would silently produce truncated
        // results.
        //
        // Scenario: scan(src/) branches into 10 sub-prefixes. With the
        // BFS cap set to 5, total_after=10 ≥ 5 fires the warn-and-break
        // path which keeps `new_frontier` as the partial result.
        let mut scanner = S3GlobMatcher::parse("src/**/*.rs".to_string(), "/", false)?;
        // High enough that we'd otherwise keep expanding past round 1.
        scanner.set_min_prefixes(100);
        scanner.set_probe_max_keys(1);
        scanner.set_max_prefixes(5);
        // Cap the per-scan sub-prefix budget high enough that all 10
        // children come through without scan-level truncation.
        scanner.set_max_parallelism(20);
        let paths: Vec<String> = (0..10)
            .flat_map(|i| vec![format!("src/d{i:02}/a.rs"), format!("src/d{i:02}/b.rs")])
            .collect();
        let engine = MockS3Engine::new(paths);

        let presult = scanner.find_prefixes(engine).await?;

        // The cap fired and kept the full new_frontier of 10 sub-dirs.
        assert!(
            presult.prefixes.len() == 10,
            "expected 10 partial-frontier prefixes after cap, got {}: {:?}",
            presult.prefixes.len(),
            presult.prefixes,
        );
        // Every kept prefix is a sub-dir of src/ — confirms we kept the
        // expanded children, not the original frontier.
        for p in &presult.prefixes {
            assert!(
                p.starts_with("src/d") && p.ends_with('/'),
                "unexpected prefix in capped result: {p:?}",
            );
        }
        // High-water mark should reflect the cap-trigger value.
        assert!(
            presult.max_prefixes_observed >= 10,
            "max_prefixes_observed must be ≥ 10 after cap, got {}",
            presult.max_prefixes_observed,
        );
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_recursive_settles_flat_dense_prefix() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        // The real `S3Engine::scan_prefixes` fires a page-budget guard
        // (`prefixes.is_empty() && pages_seen >= ceil(max/1000)`) that
        // returns `truncated=true` with no sub-prefixes for flat-dense
        // parents. The BFS treats that the same as cap-hit truncation
        // — settle the parent and let `get_all_children` re-list it.
        // The mock simulates this via `with_forced_truncation`.
        //
        // Scenario: src/dense/ pretends to be flat-dense (forced
        // truncate). src/sparse/ has one file and is probe-resolvable.
        // The two prefixes exercise different settle paths in the same
        // run.
        let mut scanner = S3GlobMatcher::parse("src/**/*.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(10);
        scanner.set_probe_max_keys(1);
        scanner.set_max_parallelism(20);
        let paths = vec![
            "src/dense/f001.rs".to_string(),
            "src/dense/f002.rs".to_string(),
            "src/dense/f003.rs".to_string(),
            "src/sparse/x.rs".to_string(),
        ];
        let engine = MockS3Engine::new(paths.clone()).with_forced_truncation(["src/dense/"]);

        let presult = scanner.find_prefixes(engine).await?;

        // src/dense/ must end up settled (not expanded into children
        // and not dropped); src/sparse/ probe-resolves to objects.
        assert!(
            presult.prefixes.contains(&"src/dense/".to_string()),
            "expected src/dense/ settled via flat-dense fallback, got: {:?}",
            presult.prefixes,
        );
        assert!(
            !presult
                .prefixes
                .iter()
                .any(|p| p.starts_with("src/dense/f")),
            "flat-dense prefix must not be expanded into per-file children, got: {:?}",
            presult.prefixes,
        );
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_recursive_mixed_probe_outcomes() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        // Within one round, the probe phase classifies each frontier
        // prefix independently: some return non-truncated (sparse →
        // pulled into objects, dropped) and some return truncated
        // (dense → handed to phase-2 scan). All previous tests force
        // every probe to truncate (probe_max_keys=1) or none to. This
        // covers the genuine mix.
        //
        // Scenario: probe_max_keys=2.
        //   a/ has 1 file → 1≤2, probe resolves, dropped from frontier.
        //   b/ has 5 files → 5>2, probe truncates → scan settles as
        //                    leaf (no sub-dirs).
        //   c/ has 3 sub-dirs each with 1 file → 3>2, probe truncates
        //                    → scan branches into 3.
        let mut scanner = S3GlobMatcher::parse("{a,b,c}/**/*.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(10);
        scanner.set_probe_max_keys(2);
        scanner.set_max_parallelism(20);
        let paths = vec![
            "a/only.rs".to_string(),
            "b/f1.rs".to_string(),
            "b/f2.rs".to_string(),
            "b/f3.rs".to_string(),
            "b/f4.rs".to_string(),
            "b/f5.rs".to_string(),
            "c/x/f.rs".to_string(),
            "c/y/f.rs".to_string(),
            "c/z/f.rs".to_string(),
        ];
        let engine = MockS3Engine::new(paths.clone());

        // a/'s probe produced 1 key (objects forwarded); b/ scan empty
        // (settled); c/ scan branched. Round 1 probes all three; later
        // rounds may probe further descendants (c/x/, c/y/, c/z/).
        let presult = scanner.find_prefixes(engine.clone()).await?;
        let probes: Vec<String> = engine
            .probe_calls
            .lock()
            .unwrap()
            .iter()
            .map(|(p, _)| p.clone())
            .collect();
        for sibling in ["a/", "b/", "c/"] {
            assert!(
                probes.iter().any(|p| p == sibling),
                "expected probe of {sibling:?} in round 1, got probes: {probes:?}",
            );
        }
        // a/ resolves via probe → not in scan-call set; b/ and c/ do.
        let scan_calls: Vec<String> = engine
            .calls
            .lock()
            .unwrap()
            .iter()
            .map(|(p, _)| p.clone())
            .collect();
        assert!(
            !scan_calls.contains(&"a/".to_string()),
            "a/ should be probe-resolved, but scan was called for it. scan calls: {scan_calls:?}",
        );
        assert!(
            scan_calls.contains(&"b/".to_string()) && scan_calls.contains(&"c/".to_string()),
            "b/ and c/ both must be scanned. scan calls: {scan_calls:?}",
        );

        // End-to-end: every matching key emitted exactly once.
        let mut result = scanner
            .get_objects(MockS3Engine::new(paths.clone()))
            .await?;
        let mut keys: Vec<String> = Vec::new();
        while let Some(batch) = result.rx.recv().await {
            for r in batch {
                if let PrefixResult::Object(obj) = r {
                    keys.push(obj.key);
                }
            }
        }
        keys.sort();
        let mut expected = paths;
        expected.sort();
        assert!(
            keys == expected,
            "expected each matching key emitted exactly once;\n  got:      {keys:?}\n  expected: {expected:?}",
        );
        // Sanity: presult had a non-trivial mix — at least one settled
        // (b/), one expanded (c/x/, c/y/, c/z/), and a/ pulled into
        // objects. Anchor the test to that mix.
        let object_keys: Vec<String> = presult
            .objects
            .iter()
            .filter_map(|o| o.key.clone())
            .collect();
        assert!(
            object_keys.contains(&"a/only.rs".to_string()),
            "a/only.rs should be in presult.objects via probe resolution, got: {object_keys:?}",
        );
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_character_class() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("src/[abc]*/zebra.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        assert_scanner_part!(&scanner.parts[0], Choice(vec!["src/a", "src/b", "src/c"]));
        assert_scanner_part!(&scanner.parts[1], Any("*"));
        assert_scanner_part!(&scanner.parts[2], OneChoice("/zebra.rs"));
        let engine = MockS3Engine::new(vec![
            "src/abc/zebra.rs".to_string(),
            "src/baz/zebra.rs".to_string(),
            "src/cat/zebra.rs".to_string(),
            "src/dog/zebra.rs".to_string(), // Should be filtered out
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        engine.assert_calls(&[("src/a", "/"), ("src/b", "/"), ("src/c", "/")]);
        assert!(prefixes == vec!["src/abc/zebra.rs", "src/baz/zebra.rs", "src/cat/zebra.rs"]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_alternation_then_any() -> Result<()> {
        let mut scanner = S3GlobMatcher::parse("literal/{foo,bar}*/baz".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        println!("scanner_parts for {}:\n{:#?}", scanner.raw, scanner.parts);

        assert_scanner_part!(
            &scanner.parts[0],
            Choice(vec!["literal/foo", "literal/bar"])
        );
        assert_scanner_part!(&scanner.parts[1], Any("*"));
        assert_scanner_part!(&scanner.parts[2], OneChoice("/baz"));

        let engine = MockS3Engine::new(vec![
            "literal/bar-stuff/baz".to_string(),
            "literal/foo-extra/baz".to_string(),
            "literal/foo/baz".to_string(),
            "literal/other/baz".to_string(), // Should be filtered out
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        engine.assert_calls(&[("literal/bar", "/"), ("literal/foo", "/")]);
        assert!(
            prefixes
                == vec![
                    "literal/bar-stuff/baz",
                    "literal/foo-extra/baz",
                    "literal/foo/baz",
                ]
        );
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_alternation_any_literal() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner =
            S3GlobMatcher::parse("literal/{foo,bar}*quux/baz".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);

        assert_scanner_part!(
            &scanner.parts[0],
            Choice(vec!["literal/foo", "literal/bar"])
        );
        assert_scanner_part!(&scanner.parts[1], Any("*"));
        assert_scanner_part!(&scanner.parts[2], OneChoice("quux/baz"));

        let engine = MockS3Engine::new(vec![
            "literal/foo-quux/baz".to_string(),
            "literal/bar-quux/baz".to_string(),
            // Should be filtered out
            "literal/foo-something-bar/baz".to_string(),
            "literal/other-quux/baz".to_string(),
            "literal/foo-quux-bar/baz".to_string(),
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        assert!(prefixes == vec!["literal/bar-quux/baz", "literal/foo-quux/baz"]);
        engine.assert_calls(&[("literal/bar", "/"), ("literal/foo", "/")]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_any_then_alternation() -> Result<()> {
        let mut scanner = S3GlobMatcher::parse("literal/*{foo,bar}/baz".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);

        assert_scanner_part!(&scanner.parts[0], OneChoice("literal/"));
        assert_scanner_part!(&scanner.parts[1], Any("*"));
        assert_scanner_part!(&scanner.parts[2], Choice(vec!["foo/baz", "bar/baz"]));

        let engine = MockS3Engine::new(vec![
            "literal/something-foo/baz".to_string(),
            "literal/other-bar/baz".to_string(),
            "literal/not-match/baz".to_string(), // Should be filtered out
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        engine.assert_calls(&[("literal/", "/")]);
        assert!(prefixes == vec!["literal/other-bar/baz", "literal/something-foo/baz"]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_literal_any_alternation() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner =
            S3GlobMatcher::parse("literal/quux*{foo,bar}/baz".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);

        assert_scanner_part!(&scanner.parts[0], OneChoice("literal/quux"));
        assert_scanner_part!(&scanner.parts[1], Any("*"));
        assert_scanner_part!(&scanner.parts[2], Choice(vec!["foo/baz", "bar/baz"]));

        let engine = MockS3Engine::new(vec![
            "literal/quux-foo/baz".to_string(),
            "literal/quux-something-bar/baz".to_string(),
            "literal/quux-other/baz".to_string(), // Should be filtered out
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        engine.assert_calls(&[("literal/quux", "/")]);
        assert!(prefixes == vec!["literal/quux-foo/baz", "literal/quux-something-bar/baz"]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_any_after_last_delimiter() -> Result<()> {
        let mut scanner = S3GlobMatcher::parse("literal/baz*/a.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);

        assert_scanner_part!(&scanner.parts[0], OneChoice("literal/baz"));
        assert_scanner_part!(&scanner.parts[1], Any("*"));
        assert_scanner_part!(&scanner.parts[2], OneChoice("/a.rs"));

        let engine = MockS3Engine::new(vec![
            "literal/baz/a.rs".to_string(),
            "literal/baz-extra/a.rs".to_string(),
            "literal/bazinga/a.rs".to_string(),
            "literal/other/a.rs".to_string(), // Should be filtered out
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        engine.assert_calls(&[("literal/baz", "/")]);
        assert!(
            prefixes
                == vec![
                    "literal/baz-extra/a.rs",
                    "literal/baz/a.rs",
                    "literal/bazinga/a.rs"
                ]
        );
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_any_and_character_class() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("literal/baz*[ab]/1.rs".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);

        assert_scanner_part!(&scanner.parts[0], OneChoice("literal/baz"));
        assert_scanner_part!(&scanner.parts[1], Any("*"));
        assert_scanner_part!(&scanner.parts[2], Choice(vec!["a/1.rs", "b/1.rs"]));

        let engine = MockS3Engine::new(vec![
            "literal/baz-a/1.rs".to_string(),
            "literal/baz-extra-b/1.rs".to_string(),
            "literal/baz-c/1.rs".to_string(), // Should be filtered out
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        engine.assert_calls(&[("literal/baz", "/")]);
        assert!(prefixes == vec!["literal/baz-a/1.rs", "literal/baz-extra-b/1.rs"]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_empty_alternative() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("src/{,tmp}/file".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        let engine = MockS3Engine::new(vec![
            "src/file".to_string(),
            "src/tmp/file".to_string(),
            "src/other/file".to_string(), // Should be filtered out
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        assert!(prefixes == vec!["src/tmp/file"]);
        let e: &[(&str, &str)] = &[];
        engine.assert_calls(e);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_empty_alternative_with_delimiter() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("src/{,tmp/}file".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        let engine = MockS3Engine::new(vec![
            "src/file".to_string(),
            "src/tmp/file".to_string(),
            "src/other/file".to_string(), // Should be filtered out
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        assert!(prefixes == vec!["src/file", "src/tmp/file"]);
        let e: &[(&str, &str)] = &[];
        engine.assert_calls(e);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_alternation_with_delimiter() -> Result<()> {
        let mut scanner = S3GlobMatcher::parse("src/{foo/bar,baz}/test".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);

        assert_scanner_part!(
            &scanner.parts[0],
            Choice(vec!["src/foo/bar/test", "src/baz/test"])
        );

        let engine = MockS3Engine::new(vec![
            "src/foo/bar/test".to_string(),
            "src/baz/test".to_string(),
            "src/foo/test".to_string(),     // Should be filtered out
            "src/foo/baz/test".to_string(), // Should be filtered out
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        assert!(prefixes == vec!["src/baz/test", "src/foo/bar/test"]);
        let e: &[(&str, &str)] = &[]; // No API calls needed since alternation is static
        engine.assert_calls(e);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_negative_class_start() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("[!a]*/foo".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        let engine = MockS3Engine::new(vec![
            "b/foo".to_string(),
            "c/foo".to_string(),
            "xyz/foo".to_string(),
            "a/foo".to_string(), // Should be filtered out
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        assert!(prefixes == vec!["b/foo", "c/foo", "xyz/foo"]);
        engine.assert_calls(&[("", "/")]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_negative_class_after_wildcard() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("*[!f]oo/*".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        let engine = MockS3Engine::new(vec![
            "zoo/a".to_string(),
            "boo/a".to_string(),
            "foo/a".to_string(),           // Should be filtered out
            "something/foo/a".to_string(), // Should be filtered out
        ]);

        let objects = scanner
            .find_prefixes(engine.clone())
            .await?
            .objects
            .into_iter()
            .map(|o| o.key.unwrap())
            .collect::<Vec<_>>();
        assert!(objects == vec!["boo/a", "zoo/a"]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_negative_class_between_alternations() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("{foo,bar}[!z]*/baz".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        let engine = MockS3Engine::new(vec![
            "foo-abc/baz".to_string(),
            "bar-def/baz".to_string(),
            "fooz/baz".to_string(),  // Should be filtered out
            "barz/baz".to_string(),  // Should be filtered out
            "other/baz".to_string(), // Should be filtered out
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        assert!(prefixes == vec!["bar-def/baz", "foo-abc/baz"]);
        engine.assert_calls(&[("bar", "/"), ("foo", "/")]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_multiple_negative_classes() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("[!a]*[!b]/foo".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        let engine = MockS3Engine::new(vec![
            "c-x/foo".to_string(),
            "d-y/foo".to_string(),
            // filtered out
            "a-b/foo".to_string(), // (both conditions fail)
            "a-x/foo".to_string(), // (first char is a)
            "c-b/foo".to_string(), // (second part starts with b)
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        assert!(prefixes == vec!["c-x/foo", "d-y/foo"]);
        engine.assert_calls(&[("", "/")]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_negative_class_with_delimiter() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("foo/[!/]/bar".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        assert_scanner_part!(&scanner.parts[0], OneChoice("foo/"));
        assert_scanner_part!(&scanner.parts[1], Any("[!/]"));
        assert_scanner_part!(&scanner.parts[2], OneChoice("/bar"));

        let engine = MockS3Engine::new(vec![
            "foo/x/bar".to_string(),
            "foo/a/bar".to_string(),
            "foo//bar".to_string(),    // Should be filtered out
            "foo/a/b/bar".to_string(), // Should be filtered out (too many segments)
            "foo///bar".to_string(),   // Should be filtered out (the excluded char)
        ]);

        let prefixes = scanner.find_prefixes(engine.clone()).await?.prefixes;
        assert!(prefixes == vec!["foo/a/bar", "foo/x/bar"]);
        engine.assert_calls(&[("foo/", "/")]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_complex_negative_pattern() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("*{foo,bar}*[!Z]/baz".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        let engine = MockS3Engine::new(vec![
            "x-foo-a/baz".to_string(),
            "y-bar-b/baz".to_string(),
            // filtered out
            "x-foo-Z/baz".to_string(), // (ends with Z)
            "y-bar-Z/baz".to_string(), // (ends with Z)
            "x-baz-a/baz".to_string(), // (middle not foo/bar)
        ]);

        let objects = scanner
            .find_prefixes(engine.clone())
            .await?
            .objects
            .into_iter()
            .map(|obj| obj.key.unwrap())
            .collect::<Vec<_>>();
        assert!(objects == vec!["x-foo-a/baz", "y-bar-b/baz"]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_file_any_then_constant() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("src/*/*zebra".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        let engine = MockS3Engine::new(vec![
            "src/foo/1_zebra".to_string(),
            "src/bar/2_zebra".to_string(),
            "src/baz/3_zebra".to_string(),
        ]);

        let objects = scanner
            .find_prefixes(engine.clone())
            .await?
            .objects
            .into_iter()
            .map(|o| o.key.unwrap())
            .collect::<Vec<_>>();
        assert!(objects == vec!["src/bar/2_zebra", "src/baz/3_zebra", "src/foo/1_zebra"]);
        Ok(())
    }

    #[tokio::test]
    async fn test_find_prefixes_sep_const_file_any_constant() -> Result<()> {
        setup_logging(Some("s3glob=trace"));
        let mut scanner = S3GlobMatcher::parse("src/*/1*zebra".to_string(), "/", false)?;
        scanner.set_min_prefixes(0);
        let engine = MockS3Engine::new(vec![
            "src/foo/1_zebra".to_string(),
            "src/bar/2_zebra".to_string(),
            "src/baz/3_zebra".to_string(),
        ]);

        let objects = scanner
            .find_prefixes(engine.clone())
            .await?
            .objects
            .into_iter()
            .map(|obj| obj.key.unwrap());
        assert!(objects.collect::<Vec<_>>() == vec!["src/foo/1_zebra"]);
        assert!(scanner.is_complete());
        Ok(())
    }

    //
    // Helpers
    //

    #[macro_export]
    macro_rules! assert_scanner_part {
        // Helper rule for match testing
        (@test_matches, $re:expr, $expected_matches:expr, !$expected_does_not_match:expr) => {
            for m in $expected_matches {
                assert!($re.is_match(m), "Regex {} failed to match {m:?}", $re.as_str());
            }
            for m in $expected_does_not_match {
                assert!(!$re.is_match(m), "Regex {} unexpectedly matched {m:?}", $re.as_str());
            }
        };

        ($part:expr, Any($expected:expr), $expected_matches:expr, !$expected_does_not_match:expr) => {
            match $part {
                Glob::Any { raw, .. } => {
                    assert!(*raw == $expected);
                    assert_scanner_part!(@test_matches, $part.re("/"), $expected_matches, !$expected_does_not_match);
                }
                other => panic!("Expected Any({:?}), got {:?}", $expected, other),
            }
        };
        ($part:expr, SyntheticAny) => {
            match $part {
                Glob::SyntheticAny => {}
                other => panic!("Expected SyntheticAny, got {:?}", other),
            }
        };
        ($part:expr, Any($expected:expr)) => {{
            let em: &[&str] = &[];
            let ednm: &[&str] = &[];
            assert_scanner_part!($part, Any($expected), em, !ednm);
        }};

        ($part:expr, NegatedAny($expected:expr), $expected_matches:expr, !$expected_does_not_match:expr) => {
            match $part {
                Glob::Any { raw } => {
                    assert!(*raw == $expected);
                    assert_scanner_part!(@test_matches, $part.re("/"), $expected_matches, !$expected_does_not_match);
                }
                other => panic!("Expected Any({:?}), got {:?}", $expected, other),
            }
        };
        ($part:expr, Recursive, $expected_matches:expr) => {
            match $part {
                Glob::Recursive => {
                    let re = $part.re("/");
                    for m in $expected_matches {
                        check!(re.is_match(m), "matching {m:?} against {}", $part.re_string("/", false));
                    }
                }
                other => panic!("Expected Recursive, got {:?}", other),
            }
        };
        ($part:expr, Recursive) => {{
            let em: &[&str] = &[];
            assert_scanner_part!($part, Recursive, em);
        }};
        // convenience rule for testing one-choice patterns
        ($part:expr, OneChoice($expected:expr)) => {
            match $part {
                Glob::Choice{ allowed, .. } => {
                    assert!(allowed.len() == 1);
                    assert!(allowed[0] == $expected);
                },
                other => panic!("Got {:?}, expected Choice([{:?}])", other, $expected),
            }
        };
        ($part:expr, Choice($expected:expr), $expected_matches:expr, !$expected_does_not_match:expr) => {
            match $part {
                Glob::Choice { allowed, .. } => {
                    check!(*allowed == $expected);
                    assert_scanner_part!(@test_matches, $part.re("/"), $expected_matches, !$expected_does_not_match);
                }
                other => panic!("Expected Choice({:?}), got {:?}", $expected, other),
            }
        };
        ($part:expr, Choice($expected:expr)) => {{
            let em: &[&str] = &[];
            let ednm: &[&str] = &[];
            assert_scanner_part!($part, Choice($expected), em, !ednm);
        }};
    }
}
